services:

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./WebApi/Images:/usr/share/nginx/html

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: "Your_password123"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"

  webapi:
    image: ${DOCKER_REGISTRY-}webapi
    build:
      context: .
      dockerfile: WebAPI/Dockerfile
    depends_on:
      - sqlserver
    environment:
      - connectionstrings__DefaultConnection=Server=sqlserver,1433;Database=master;User Id=sa;Password=Your_password123;TrustServerCertificate=True
    ports:
      - "5000:8080"
      - "5001:8081"
    volumes:
      - ./WebApi/Images:/images